name: Release
on:
  release:
    types: [published]

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag
        id: set_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: PR Time
        run: |
          HASH=$(echo $(date +'%s') | shasum -a 256 |  cut -c -8)
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          git checkout -b tmp-$HASH
          echo "# \`$HASH\`" >> test.md
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -s -m "ci: auto commit"
          git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
          RELEASE_BODY=$(gh release view v${{ steps.set_tag.outputs.tag }} --json body --jq '.body')
          gh pr create \
            -B main \
            -H $(git rev-parse --abbrev-ref HEAD) \
            -t "🤖 ${{ steps.set_tag.outputs.tag }}" \
            -b $RELEASE_BODY \
            -r thiskevinwang
          
