name: Release
on:
  release:
    types: [published]

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag
        id: set_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: PR Time
        run: |
          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
# git checkout -b tmp-$GITHUB_SHA
# git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
# echo "test" >> test.md
# git add .
# git commit -s -m "ci: auto commit"
# gh pr create -B main -t ${{ steps.set_tag.outputs.tag }} -b ${{ steps.set_tag.outputs.tag }} --fill -H $(git rev-parse --abbrev-ref HEAD)
# gh pr edit --add-reviewer thiskevinwang
# gh pr edit --body "$(gh release view v${{ steps.set_tag.outputs.tag }} --json body --jq '.body')"
          
