# name: LEAVE NAME BLANK. This allows for easy linking to **this** workflow
#       file with: ${{github.server_url}}/${{github.repository}}/blob/main/${{github.workflow}}
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - "website/**"

jobs:
  check-for-tfc-docs-changes:
    # Do not check Automated PRs opened by the digital-content-events
    # GH App. These are expected to modify TFC files.
    if: ${{github.actor}} != "digital-content-events"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for file in $(gh pr view ${{ github.event.number }} --json files -q '.files[].path'); do
            # -E is for extended pattern matching
            # -q is for quiet mode

            # This line allows us to ignore grep's `exit 1` on no matches.
            matches=$(cat $file | { grep -Eq 'source:\s+terraform-docs-common' || true; })

            # if matches length > 0, then the file contains the string
            if [ ${#matches} -gt 0 ]; then
                exit 1
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Post a PR comment if TFC files have been modified
  post-pr-warning:
    runs-on: ubuntu-latest
    needs: [check-for-tfc-docs-changes]
    if: failure()
    steps:
      - name: Echo if failed
        run: |
          echo "::warning::TFC Docs changed"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            > **Warning**: TFC Docs Changed [^1]
            >
            > This PR contains changes to documentation files from the [`terraform-docs-common` repository](https://github.com/hashicorp/terraform-docs-common).
            > These files contain a frontmatter field, `source: terraform-docs-common`, and they are automatically copied into this repository at app deadline. Refer to the [README](https://github.com/hashicorp/ptfe-releases#maintaining-tfe-website-documentation) for details.
            >
            > - TFE releases: Do not edit files with the `source: terraform-docs-common` header. Instead, change these files in the `terraform-docs-common` repository before app deadline.
            >
            > - TFE patches: You may need to edit files with the `source: terraform-docs-common` header so that your documentation changes appear in the patch release. If you edit these files, you must also open a pull request with the same changes in the [`terraform-docs-common` repository](https://github.com/hashicorp/terraform-docs-common).
            >
            > Ignore this comment if you already reversed these changes.
            >
            [^1]: For details on this workflow, refer to [${{github.workflow}}](${{github.server_url}}/${{github.repository}}/blob/main/${{github.workflow}})
