on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - "website/**"

jobs:
  check-for-tfc-docs-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          for file in $(gh pr view ${{ github.event.number }} --json files -q '.files[].path'); do
            # -E is for extended pattern matching
            # -q is for quiet mode
            grep -Eq 'tfc_only:\s+true' $file;

            # if grep returns 0, then the file contains the string
            if [ $? -eq 0 ]; then
                exit 1;
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-if-failed:
    runs-on: ubuntu-latest
    needs: [check-for-tfc-docs-changes]
    if: always() && needs.check-for-tfc-docs-changes.result == 'failure'
    steps:
      - name: Echo if failed
        run: echo "TFC Docs changed"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            > **Warning**: TFC Docs changed [^1]
            >
            > This PR contains changes to documentation files that originate from [terraform-docs-common](https://github.com/hashicorp/terraform-docs-common).
            > These files contain a frontmatter field, `tfc_only: true`.
            >
            > These files are not meant to be edited directly.
            >
            > Any modifications should ideally be made in [terraform-docs-common](https://github.com/hashicorp/terraform-docs-common).
            > If they absolutely must be made here, please make sure to open an equivalent PR in the original repository.
            >
            > If necessary reversions were already made, feel free to ignore this comment.
            >
            [^1]: For details on this particular workflow, see [${{github.workflow}}](${{github.workflow}})
