name: Input Mapping Example

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: The pull request action
        required: true
        options:
          - assigned
          - auto_merge_disabled
          - auto_merge_enabled
          - closed
          - converted_to_draft
          - edited
          - labeled
          - locked
          - opened
          - ready_for_review
          - reopened
          - review_request_removed
          - review_requested
          - synchronize
          - unassigned
          - synchronize
          - unlabeled
          - unlocked
      author:
        type: string
        required: true
        description: The pull request author
      dry_run:
        type: boolean
        description: Dry run?
        required: false

jobs:
  map_inputs:
    runs-on: ubuntu-latest
    env:
      pr_action: ${{ github.event.action                  || inputs.action }}
      pr_author: ${{ github.event.pull_request.user.login || inputs.author }}
    outputs:
      pr_action: ${{ github.event.action                  || inputs.action }}
      pr_author: ${{ github.event.pull_request.user.login || inputs.author }}
    steps:
      - run: |
          echo "ACTION=${{env.pr_action}}" >> $GITHUB_ENV
          echo "AUTHOR=${{env.pr_author}}" >> $GITHUB_ENV
          echo "### \`map_inputs\`"          >> $GITHUB_STEP_SUMMARY
          echo "ACTION=${{env.pr_action}}" >> $GITHUB_STEP_SUMMARY
          echo "AUTHOR=${{env.pr_author}}" >> $GITHUB_STEP_SUMMARY
          echo ""                          >> $GITHUB_STEP_SUMMARY
  summary:
    needs: map_inputs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### \`summary\`"                                                  >> $GITHUB_STEP_SUMMARY
          echo ""                                                               >> $GITHUB_STEP_SUMMARY
          echo "**env.ACTION**: ${{env.ACTION}}"                                >> $GITHUB_STEP_SUMMARY
          echo "**env.AUTHOR**: ${{env.AUTHOR}}"                                >> $GITHUB_STEP_SUMMARY
          echo ""                                                               >> $GITHUB_STEP_SUMMARY
          echo "**outputs.pr_action**: ${{needs.map_inputs.outputs.pr_action}}" >> $GITHUB_STEP_SUMMARY
          echo "**outputs.pr_author**: ${{needs.map_inputs.outputs.pr_author}}" >> $GITHUB_STEP_SUMMARY
