on:
  workflow_dispatch:
    inputs:
      log_level:
        description: 'log level'
        required: false
      environment:
        type: environment
        description: Select the environment
        required: false
      boolean:
        type: boolean
        description: True or False
        required: false
      choice:
        type: choice
        description: Make a choice
        required: false
        options:
        - trace
        - debug
        - info
        - warn
        - error
        - fatal

jobs:
  upload-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'npm'
      - run: npm install
      - run: npm run log
