name: Pretty Log

on:
  workflow_dispatch:
    inputs:
      log_level:
        type: choice
        description: Log level
        required: false
        options:
        - trace
        - debug
        - info
        - warn
        - error
        - fatal
      dry_run:
        type: boolean
        description: Dry run?
        required: false

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'npm'
      - run: npm install
      - run: npm run log
